@echo off
setlocal

set "URL=http://localhost:8080/movie-recommendation/simulator/movie"

REM Add movies
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Batman\", \"rank\": 95}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Batwoman\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Batboy\", \"rank\": 88}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Black Panther\", \"rank\": 93}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Black Widow\", \"rank\": 89}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Blade\", \"rank\": 84}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Brave\", \"rank\": 80}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Bridesmaids\", \"rank\": 77}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Brooklyn\", \"rank\": 82}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Cars\", \"rank\": 79}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Cinderella\", \"rank\": 85}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Captain America\", \"rank\": 91}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Captain Marvel\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Coco\", \"rank\": 92}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Creed\", \"rank\": 86}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Deadpool\", \"rank\": 94}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Doctor Strange\", \"rank\": 89}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Dune\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Eternals\", \"rank\": 82}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Encanto\", \"rank\": 87}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Everything Everywhere All at Once\", \"rank\": 96}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Frozen\", \"rank\": 88}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Forrest Gump\", \"rank\": 94}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Gladiator\", \"rank\": 89}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Gravity\", \"rank\": 87}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Guardians of the Galaxy\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Harry Potter\", \"rank\": 93}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Hulk\", \"rank\": 85}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Inception\", \"rank\": 97}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Interstellar\", \"rank\": 96}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Iron Man\", \"rank\": 92}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Joker\", \"rank\": 91}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Jumanji\", \"rank\": 84}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Justice League\", \"rank\": 86}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Luca\", \"rank\": 83}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Logan\", \"rank\": 89}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Moana\", \"rank\": 86}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Mulan\", \"rank\": 87}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"No Time to Die\", \"rank\": 85}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Ratatouille\", \"rank\": 92}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Shang-Chi\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Shazam\", \"rank\": 84}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Soul\", \"rank\": 89}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Spider-Man: Homecoming\", \"rank\": 94}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Spiderman\", \"rank\": 91}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Spiderverse\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Thor\", \"rank\": 88}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Wonder Woman\", \"rank\": 90}"
curl -s -X POST %URL% -H "Content-Type: application/json" -d "{\"name\": \"Zootopia\", \"rank\": 85}"

echo All movies added successfully!
pause
