#!/bin/bash

endpoint="http://localhost:8080/movie-recommendation/simulator/movie"

declare -a movies=(
  "Batman,95"
  "Batwoman,90"
  "Batboy,88"
  "Black Panther,93"
  "Black Widow,89"
  "Blade,84"
  "Brave,80"
  "Bridesmaids,77"
  "Brooklyn,82"
  "Cars,79"
  "Cinderella,85"
  "Captain America,91"
  "Captain Marvel,90"
  "Coco,92"
  "Creed,86"
  "Deadpool,94"
  "Doctor Strange,89"
  "Dune,90"
  "Eternals,82"
  "Encanto,87"
  "Everything Everywhere All at Once,96"
  "Frozen,88"
  "Forrest Gump,94"
  "Gladiator,89"
  "Gravity,87"
  "Guardians of the Galaxy,90"
  "Harry Potter,93"
  "Hulk,85"
  "Inception,97"
  "Interstellar,96"
  "Iron Man,92"
  "Joker,91"
  "Jumanji,84"
  "Justice League,86"
  "Luca,83"
  "Logan,89"
  "Moana,86"
  "Mulan,87"
  "No Time to Die,85"
  "Ratatouille,92"
  "Shang-Chi,90"
  "Shazam,84"
  "Soul,89"
  "Spider-Man: Homecoming,94"
  "Spiderman,91"
  "Spiderverse,90"
  "Thor,88"
  "Wonder Woman,90"
  "Zootopia,85"
)

for entry in "${movies[@]}"; do
  name="${entry%%,*}"
  rank="${entry##*,}"
  curl -s -X POST "$endpoint" -H "Content-Type: application/json" \
       -d "{\"name\": \"$name\", \"rank\": $rank}"
done

echo "✅ Populated 50 movies."
